project:
  type: book

book:
  title: "ECEN639: Pattern Recognition"
  author: "Jane Doe"
  date: "8/25/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - ch1.qmd
    - hw/hw1.qmd
    - summary.qmd
    - ref.qmd

bibliography: ref.bib

format:
  html:
    theme: cosmo



