project:
  type: book

book:
  title: "ECEN649: Pattern Recognition"
  author: "Shao-Ting Chiu"
  date: "20221211"
  favicon: img/favicon.png
  reader-mode: true
  navbar:
    background: maroon
    right:
      - icon: github
        href: https://github.com/stevengogogo/ECEN649_Pattern-Recognition
        aria-label: GitHub
  chapters:
    - index.qmd
    - part: "**Lecture Notes**"
      chapters:
        - intro.qmd
        - ch1.qmd
        - ch2.qmd
        - ch3.qmd
        - ch4.qmd
    - part: "**Assignments**"
      chapters:
        - hw/hw1.qmd
        - hw/hw2.qmd
        - hw/hw3.qmd
        - hw/hw4.qmd
        - hw/hw4_p6-12_right_cv.ipynb
        - hw/hw5.ipynb
    - part: "**Final Project**"
      chapters:
        - final_project.qmd
        - final_project/script/HMC_Copy_of_EXP_fit_time_window.ipynb
        - final_project/script/EXP_data_visualization.ipynb
        - final_project/script/jax_basic.ipynb
        - final_project/script/jax_bnn.ipynb
    - ref.qmd

bibliography: ref.bib

format:
  html:
    theme: 
      light: flatly
      dark: darkly

