project:
  type: book

book:
  title: "ECEN639: Pattern Recognition"
  author: "Shao-Ting Chiu"
  date: today
  repo-url: https://github.com/stevengogogo/ECEN649_Pattern-Recognition
  favicon: img/favicon.png
  chapters:
    - index.qmd
    - intro.qmd
    - ch1.qmd
    - ch2.qmd
    - hw/hw1.qmd
    - hw/hw2.qmd
    - hw/hw3.qmd
    - summary.qmd
    - ref.qmd

bibliography: ref.bib

format:
  html:
    theme: 
      light: flatly
      dark: darkly

