# Preface {.unnumbered}


> This course aims to introduce the basic elements of Pattern Recognition,focusing on critical mathematical and statistical aspects underlying classification. After a review of probability theory, we discuss fundamental concepts of classification, such as the optimal classifier and classification consistency, followed by a study of several families of classification rules, error estimation, dimensionality reduction, and model selection, including an introduction to Vapnik-Chervonenkis theory. Time permitting, clustering and regression will be also covered. Performance will be assessed by means of a midterm, problem sets, and a final class project. There will be coding assignments based on python and sklearn as part of the problem sets. Previous coursework in probability theory and programming skills are assumed. --- *ECEN649 Syllabus*

- Course: ECEN649 (special topic), 2022Fall
- Instructor: [Dr. Ulisses Braga-Neto](https://engineering.tamu.edu/electrical/profiles/ubraganeto.html)


- [Book Website](https://braganeto.engr.tamu.edu/book-website/)
- [Final project](https://github.com/stevengogogo/ECEN649_FinalProject/tree/main)